import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({
  subsets:['latin'],
  weight: ['300','400','500','700']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${ubuntu.className} antialiased`}
      >
        <SidebarProvider>
      <AppSidebar/>
      <main className="w-full">
        <SidebarTrigger side="right"/>
        {children}
      </main>
    </SidebarProvider>
      </body>
    </html>
  );
}
